version: '3.0'
services:
  mongo-db: # 相关文档 https://hub.docker.com/_/mongo
    container_name: mongo-db
    # environment:
      # - MONGO_INITDB_ROOT_USERNAME=lNhOii&W6TD&PLgm!@Bla@k&^#zs%Anv
      # - MONGO_INITDB_ROOT_PASSWORD=lNhOii&W6TD&PLgm!@Bla@k&^#zs%Anv
    build:
      context: .
      args:
        - MONGO_VER=4.2
    ports:
      - "27017:27017"
    volumes:
      - ./data:/var/lib/mongodb
      - ./logs:/var/log/mongodb
      - ./mongod.conf:/etc/mongod.conf
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rain
      ME_CONFIG_MONGODB_ADMINPASSWORD: rain
    restart: always