version: '3.0'
services:
  redis-db: # 相关文档 https://hub.docker.com/_/redis
    build:
      context: .
      args:
        - REDIS_VER=5
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./data:/data
      - ./logs:/var/log
    restart: always